# Generated by Django 2.2 on 2021-07-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_auto_20210720_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='school3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='school4',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
