# Generated by Django 2.2 on 2021-07-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0003_auto_20210721_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='grad3',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='grad4',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
