# Generated by Django 2.2 on 2021-07-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0004_auto_20210722_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='school3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
