# Generated by Django 2.2 on 2021-07-13 03:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0004_auto_20210709_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date_from',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today, message='Date must be in the past')]),
        ),
        migrations.AlterField(
            model_name='education',
            name='date_to',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employment',
            name='date_from',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today, message='Date must be in the past')]),
        ),
        migrations.AlterField(
            model_name='employment',
            name='date_to',
            field=models.DateField(),
        ),
    ]
