# Generated by Django 2.2 on 2021-07-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0006_auto_20210713_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='site',
        ),
        migrations.AddField(
            model_name='social',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='linkedin',
            field=models.URLField(null=True),
        ),
    ]
