# Generated by Django 2.2 on 2021-07-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0007_auto_20210714_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='selected',
        ),
        migrations.AddField(
            model_name='skill',
            name='selected1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='skill',
            name='selected2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='skill',
            name='selected3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='skill',
            name='selected4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='skill',
            name='selected5',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='skill',
            name='selected6',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='skill',
            name='selected7',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='skill',
            name='selected8',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='skill',
            name='selected9',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='social',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
