# Generated by Django 2.2 on 2021-07-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0008_auto_20210715_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='facebook',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='social',
            name='github',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='social',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='social',
            name='twitter',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
