# Generated by Django 2.2 on 2021-07-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0009_auto_20210715_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date_to',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='date_to',
            field=models.DateField(blank=True),
        ),
    ]
