# Generated by Django 2.2 on 2021-07-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0011_remove_education_date_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
