from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('about', views.about),
    path('contact', views.contact),
    path('media', views.media),
    path('recommend', views.recommend),
    path('logreg', views.logreg),
    path('register', views.register),
    path('login', views.login),
    path('newresume/<int:user_id>', views.newresume),
    path('resumehome/<int:user_id>', views.resumehome),
    path('personalinfo/<int:user_id>', views.personalinfo),
    path('social', views.social),
    path('objectiveandskill', views.objectiveandskill),
    path('objandskill', views.objandskill),
    path('experiencepage', views.experiencepage),
    path('experience', views.experience),
    path('employmentpage', views.employmentpage),
    path('employment', views.employment),
    path('educationpage', views.educationpage),
    path('education', views.education),
    path('additionalpage', views.additionalpage),
    path('additional', views.additional),
    path('picturepage', views.picturepage),
    path('picture', views.picture),
    path('templatepage', views.templatepage),
    path('template1/<int:user_id>', views.template1),
    path('template2/<int:user_id>', views.template2),
    path('template3/<int:user_id>', views.template3),
    path('template4/<int:user_id>', views.template4),
    path('editpersonalpage', views.editpersonalpage),
    path('editcontact', views.editcontact),
    path('editobjandskillpage', views.editobjandskillpage),
    path('editobjective', views.editobjective),
    path('editexperiencepage', views.editexperiencepage),
    path('editexperience', views.editexperience),
    path('editemploymentpage', views.editemploymentpage),
    path('editemployment', views.editemployment),
    path('editeducationpage', views.editeducationpage),
    path('editeducation', views.editeducation),
    path('editadditionalpage', views.editadditionalpage),
    path('editadditional', views.editadditional),
    path('editpicturepage', views.editpicturepage),
    path('editpicture', views.editpicture),
    path('delete_pic/<int:user_id>', views.delete_pic),
    path('delete_profilepic/<int:user_id>', views.delete_profilepic),
    path('logout', views.logout),
]